/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilan;

/**
 *
 * @author DanarKristiawan
 */
public class DataSupplier extends javax.swing.JPanel {

    /**
     * Creates new form DataSupplier
     */
    public DataSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelKatBrng = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblnmSupplier = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtkdSupplier = new javax.swing.JTextField();
        txtnmSupplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsup = new javax.swing.JTable();
        lblkdSupplier = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        bcreate = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        lbltelp = new javax.swing.JLabel();
        txttelp = new javax.swing.JTextField();

        lblid.setText("ID ");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Supplier");

        lblnmSupplier.setText("Nama Supplier");

        tblsup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Kategori", "Kode Kategori", "Nama Kategori", "Deskripsi"
            }
        ));
        tblsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsup);

        lblkdSupplier.setText("Kode Supplier");

        lblalamat.setText("Alamat");

        bcreate.setText("Create Data");
        bcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcreateActionPerformed(evt);
            }
        });

        bupdate.setText("Update Data");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        lbltelp.setText("No Telepon");

        javax.swing.GroupLayout PanelKatBrngLayout = new javax.swing.GroupLayout(PanelKatBrng);
        PanelKatBrng.setLayout(PanelKatBrngLayout);
        PanelKatBrngLayout.setHorizontalGroup(
            PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKatBrngLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(209, 209, 209))
            .addGroup(PanelKatBrngLayout.createSequentialGroup()
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKatBrngLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelKatBrngLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(bupdate)
                        .addGap(46, 46, 46)
                        .addComponent(bcreate))
                    .addGroup(PanelKatBrngLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnmSupplier)
                            .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblkdSupplier)
                                .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblalamat)
                            .addComponent(lbltelp))
                        .addGap(23, 23, 23)
                        .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(txtkdSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnmSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttelp))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelKatBrngLayout.setVerticalGroup(
            PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKatBrngLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkdSupplier)
                    .addComponent(txtkdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnmSupplier)
                    .addComponent(txtnmSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblalamat)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelp)
                    .addComponent(txttelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(PanelKatBrngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bupdate)
                    .addComponent(bcreate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelKatBrng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelKatBrng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupMouseClicked
        int bar = tblsup.getSelectedRow();
        if (bar != -1) {
            txtID.setText(tabmode.getValueAt(bar, 0).toString());
            txtkdSupplier.setText(tabmode.getValueAt(bar, 1).toString());
            txtnmSupplier.setText(tabmode.getValueAt(bar, 2).toString());
            txtalamat.setText(tabmode.getValueAt(bar, 3).toString());
        }// TODO add your handling code here:
    }//GEN-LAST:event_tblsupMouseClicked

    private void bcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcreateActionPerformed
        if (txtID.getText().isEmpty() || txtkdSupplier.getText().isEmpty() || txtnmSupplier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID, Kode Kategori, dan Nama Kategori harus diisi!");
            return;
        }

        String sql = "INSERT INTO kategori (id, kode_kategori, nama_kategori, deskripsi) VALUES (?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtID.getText());
            stat.setString(2, txtkdSupplier.getText());
            stat.setString(3, txtnmSupplier.getText());
            stat.setString(4, txtalamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txtID.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bcreateActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diupdate terlebih dahulu!");
            return;
        }

        String sql = "UPDATE kategori SET kode_kategori = ?, nama_kategori = ?, deskripsi = ? WHERE id = ?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkdSupplier.getText());
            stat.setString(2, txtnmSupplier.getText());
            stat.setString(3, txtalamat.getText());
            stat.setString(4, txtID.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
            kosong();
            txtID.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diupdate: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelKatBrng;
    private javax.swing.JButton bcreate;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblkdSupplier;
    private javax.swing.JLabel lblnmSupplier;
    private javax.swing.JLabel lbltelp;
    private javax.swing.JTable tblsup;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtkdSupplier;
    private javax.swing.JTextField txtnmSupplier;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables
}
