/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.mindrot.jbcrypt.BCrypt;
import koneksi.koneksi;


/**
 *
 * @author Who_Im_I
 */
//deklarasi panel dan button yang berada pada tampilan utama aplikasi
public class Login extends javax.swing.JPanel {
private JPanel Panel1, Panel2, Panel3;  //deklarasi panel dan button yang berada pada tampilan utama aplikasi
private JButton Homemaster, transaksi, laporan, exit; //deklarasi panel dan button yang berada pada tampilan utama aplikasi


public Login(JPanel Panel1, JPanel Panel2, JPanel Panel3,
             JButton Homemaster, JButton transaksi, JButton laporan, JButton exit) {
    initComponents();
    this.Panel1 = Panel1;
    this.Panel2 = Panel2;
    this.Panel3 = Panel3;
    this.Homemaster = Homemaster;
    this.transaksi = transaksi;
    this.laporan = laporan;
    this.exit = exit;
    //Constructor menerima referensi ke panel dan tombol yang dimiliki oleh frame utama.
    //Ini agar tombol dan panel tersebut bisa dikendalikan dari class ini (seperti mengubah setVisible atau mengganti isi panel).
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jCheckBoxShowPassword = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(271, 322));
        setMinimumSize(new java.awt.Dimension(271, 322));
        setPreferredSize(new java.awt.Dimension(271, 322));
        setLayout(new java.awt.BorderLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setMaximumSize(new java.awt.Dimension(271, 322));
        loginPanel.setPreferredSize(new java.awt.Dimension(271, 322));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/userLogo.png"))); // NOI18N
        jLabel2.setText("USER");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/PassLogo.png"))); // NOI18N
        jLabel3.setText("PASSWORD");

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Logologin.png"))); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jCheckBoxShowPassword.setText("View Password");
        jCheckBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBoxShowPassword)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxShowPassword)
                .addGap(18, 18, 18)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(loginPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String usernameInput = user.getText().trim();
    String passwordInput = new String(pass.getPassword()).trim();

    if (usernameInput.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tolong isi user id terlebih dahulu");
        user.requestFocus();
        return;
    }

    if (passwordInput.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tolong isi password terlebih dahulu");
        pass.requestFocus();
        return;
    }

    // Buka koneksi baru di dalam blok try-with-resources
    try (Connection conn = new koneksi().connect()) {

        if (conn == null || conn.isClosed()) {
            JOptionPane.showMessageDialog(null, "Koneksi ke database gagal.");
            return;
        }

        String sql = "SELECT password FROM users WHERE username = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, usernameInput);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    String hashedPassword = rs.getString("password");

                    if (BCrypt.checkpw(passwordInput, hashedPassword)) {
                        // Login berhasil
                        Homemaster.setVisible(true);
                        transaksi.setVisible(true);
                        laporan.setVisible(true);
                        exit.setVisible(true);

                        Panel1.setVisible(true);
                        Panel2.setVisible(true);

                        Panel2.removeAll();
                        Panel2.setLayout(new BorderLayout());
                        Panel2.add(new MenuMaster(Panel3), BorderLayout.CENTER);
                        Panel2.revalidate();
                        Panel2.repaint();

                        Panel3.removeAll();
                        Panel3.revalidate();
                        Panel3.repaint();
                    } else {
                        JOptionPane.showMessageDialog(null, "Password salah!");
                        pass.setText("");
                        pass.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Username tidak ditemukan!");
                    user.requestFocus();
                }
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat login:\n" + e.getMessage());
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void jCheckBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxShowPassword.isSelected()) {
            // Jika checkbox dicentang, tampilkan karakter sandi asli (char 0 berarti karakter asli)
            pass.setEchoChar((char) 0);
        } else {
            // Jika checkbox tidak dicentang, sembunyikan karakter sandi dengan '*'
            //            txtPassword.setEchoChar(txtPassword.getDefaultEchoChar());
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxShowPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
