/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Who_Im_I
 */
public class MenuLaporan extends javax.swing.JPanel {

    private JPanel panelTarget;  // Tipe diperbaiki jadi JPanel

    public MenuLaporan(JPanel panelTarget) {
        this.panelTarget = panelTarget;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaporan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        laporstok = new javax.swing.JButton();
        laporBmasuk = new javax.swing.JButton();
        LaporBkeluar = new javax.swing.JButton();
        Laporsup = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelLaporan.setMaximumSize(new java.awt.Dimension(271, 322));
        panelLaporan.setMinimumSize(new java.awt.Dimension(271, 322));
        panelLaporan.setPreferredSize(new java.awt.Dimension(271, 322));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Laporan");

        laporstok.setBackground(new java.awt.Color(255, 255, 255));
        laporstok.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        laporstok.setText("Laporan Stok");
        laporstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporstokActionPerformed(evt);
            }
        });

        laporBmasuk.setBackground(new java.awt.Color(255, 255, 255));
        laporBmasuk.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        laporBmasuk.setText("Laporan Barang Masuk");
        laporBmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporBmasukActionPerformed(evt);
            }
        });

        LaporBkeluar.setBackground(new java.awt.Color(255, 255, 255));
        LaporBkeluar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LaporBkeluar.setText("Laporan Barang Keluar");
        LaporBkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporBkeluarActionPerformed(evt);
            }
        });

        Laporsup.setBackground(new java.awt.Color(255, 255, 255));
        Laporsup.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Laporsup.setText("Laporan Supplier");
        Laporsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporsupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Laporsup, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LaporBkeluar)
                    .addComponent(laporBmasuk)
                    .addComponent(laporstok, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(laporstok)
                .addGap(26, 26, 26)
                .addComponent(laporBmasuk)
                .addGap(26, 26, 26)
                .addComponent(LaporBkeluar)
                .addGap(26, 26, 26)
                .addComponent(Laporsup)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        add(panelLaporan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void laporstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporstokActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_laporstokActionPerformed

    private void laporBmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporBmasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporBmasukActionPerformed

    private void LaporBkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporBkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporBkeluarActionPerformed

    private void LaporsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporsupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporsupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LaporBkeluar;
    private javax.swing.JButton Laporsup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporBmasuk;
    private javax.swing.JButton laporstok;
    private javax.swing.JPanel panelLaporan;
    // End of variables declaration//GEN-END:variables
}
