/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Who_Im_I
 */
public class MenuMaster extends javax.swing.JPanel {

    private JPanel panelTarget;  // Tipe diperbaiki jadi JPanel

    public MenuMaster(JPanel panelTarget) {
        this.panelTarget = panelTarget;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        databrng = new javax.swing.JButton();
        datakat = new javax.swing.JButton();
        datasup = new javax.swing.JButton();
        datauser = new javax.swing.JButton();
        datalok = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(271, 322));
        jPanel6.setMinimumSize(new java.awt.Dimension(271, 322));
        jPanel6.setPreferredSize(new java.awt.Dimension(271, 322));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/86493543_7136d4.jpg"))); // NOI18N
        jLabel1.setText("Master Data");

        databrng.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        databrng.setText("Data Barang");
        databrng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databrngActionPerformed(evt);
            }
        });

        datakat.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        datakat.setText("Data Kategori");
        datakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakatActionPerformed(evt);
            }
        });

        datasup.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        datasup.setText("Data Supplier");
        datasup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasupActionPerformed(evt);
            }
        });

        datauser.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        datauser.setText("Data User");
        datauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datauserActionPerformed(evt);
            }
        });

        datalok.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        datalok.setText("Data Lokasi");
        datalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datalokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datakat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datasup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(databrng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datauser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datalok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(databrng)
                .addGap(26, 26, 26)
                .addComponent(datakat)
                .addGap(26, 26, 26)
                .addComponent(datasup)
                .addGap(26, 26, 26)
                .addComponent(datauser)
                .addGap(26, 26, 26)
                .addComponent(datalok)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void databrngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databrngActionPerformed
    panelTarget.removeAll();
    panelTarget.setLayout(new BorderLayout());
    panelTarget.add(new DataBarang(), BorderLayout.CENTER);
    panelTarget.revalidate();
    panelTarget.repaint();  // TODO add your handling code here:
    }//GEN-LAST:event_databrngActionPerformed

    private void datakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakatActionPerformed
    panelTarget.removeAll();
    panelTarget.setLayout(new BorderLayout());
    //new Kategori().setVisible(true);
    panelTarget.add(new Kategori(), BorderLayout.CENTER);
    panelTarget.revalidate();
    panelTarget.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_datakatActionPerformed

    private void datasupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasupActionPerformed
    panelTarget.removeAll();
    panelTarget.setLayout(new BorderLayout());
    //new Kategori().setVisible(true);
    panelTarget.add(new DataSupplier(), BorderLayout.CENTER);
    panelTarget.revalidate();
    panelTarget.repaint(); 
// TODO add your handling code here:
    }//GEN-LAST:event_datasupActionPerformed

    private void datauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datauserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datauserActionPerformed

    private void datalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datalokActionPerformed
    panelTarget.removeAll();
    panelTarget.setLayout(new BorderLayout());
    //new Kategori().setVisible(true);
    panelTarget.add(new DataLokasi(), BorderLayout.CENTER);
    panelTarget.revalidate();
    panelTarget.repaint();    
// TODO add your handling code here:
    }//GEN-LAST:event_datalokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton databrng;
    private javax.swing.JButton datakat;
    private javax.swing.JButton datalok;
    private javax.swing.JButton datasup;
    private javax.swing.JButton datauser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
