package tampilan;

import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Who_Im_I
 */
public class MenuLaporan extends javax.swing.JPanel {

    private JPanel panelTarget;  // Tipe diperbaiki jadi JPanel

    public MenuLaporan(JPanel panelTarget) {
        this.panelTarget = panelTarget;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaporan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        laporstok = new javax.swing.JButton();
        laporBmasuk = new javax.swing.JButton();
        LaporBkeluar = new javax.swing.JButton();
        Laporsup = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelLaporan.setBackground(new java.awt.Color(255, 255, 255));
        panelLaporan.setMaximumSize(new java.awt.Dimension(271, 322));
        panelLaporan.setMinimumSize(new java.awt.Dimension(271, 322));
        panelLaporan.setPreferredSize(new java.awt.Dimension(271, 322));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/laporan.jpeg"))); // NOI18N
        jLabel1.setText("Laporan");

        laporstok.setBackground(new java.awt.Color(255, 255, 255));
        laporstok.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        laporstok.setText("Laporan Stok");
        laporstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporstokActionPerformed(evt);
            }
        });

        laporBmasuk.setBackground(new java.awt.Color(255, 255, 255));
        laporBmasuk.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        laporBmasuk.setText("Laporan Barang Masuk");
        laporBmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporBmasukActionPerformed(evt);
            }
        });

        LaporBkeluar.setBackground(new java.awt.Color(255, 255, 255));
        LaporBkeluar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LaporBkeluar.setText("Laporan Barang Keluar");
        LaporBkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporBkeluarActionPerformed(evt);
            }
        });

        Laporsup.setBackground(new java.awt.Color(255, 255, 255));
        Laporsup.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Laporsup.setText("Laporan Supplier");
        Laporsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporsupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(laporBmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LaporBkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Laporsup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(laporstok)
                .addGap(26, 26, 26)
                .addComponent(laporBmasuk)
                .addGap(26, 26, 26)
                .addComponent(LaporBkeluar)
                .addGap(26, 26, 26)
                .addComponent(Laporsup)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        add(panelLaporan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void laporstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporstokActionPerformed
      try {
    // Lokasi file .jasper (file hasil compile dari .jrxml)
    String namaFile = "src/tampilan/stock_barang.jasper";
    Connection con = new koneksi().connect();
    // Parameter untuk report, bisa dikosongkan jika tidak ada parameter
    HashMap<String, Object> parameter = new HashMap<>();
    // File report
    File report_file = new File(namaFile);
    // Load report (gunakan variabel report_file agar konsisten)
    JasperReport report = (JasperReport) JRLoader.loadObject(report_file);
    // Isi report dengan data dari database
    JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameter, con);
    // Tampilkan report
    JasperViewer.viewReport(jasperPrint, false);
    JasperViewer.setDefaultLookAndFeelDecorated(true);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error menampilkan laporan: " + e.getMessage());
}           // TODO add your handling code here:
    }//GEN-LAST:event_laporstokActionPerformed

    private void laporBmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporBmasukActionPerformed
      try {
    // Lokasi file .jasper (file hasil compile dari .jrxml)
    String namaFile = "src/tampilan/LAPORAN_BARANG_MASUK.jasper";
    Connection con = new koneksi().connect();
    // Parameter untuk report, bisa dikosongkan jika tidak ada parameter
    HashMap<String, Object> parameter = new HashMap<>();
    // File report
    File report_file = new File(namaFile);
    // Load report (gunakan variabel report_file agar konsisten)
    JasperReport report = (JasperReport) JRLoader.loadObject(report_file);
    // Isi report dengan data dari database
    JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameter, con);
    // Tampilkan report
    JasperViewer.viewReport(jasperPrint, false);
    JasperViewer.setDefaultLookAndFeelDecorated(true);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error menampilkan laporan: " + e.getMessage());
}           // TODO add your handling code here:
    }//GEN-LAST:event_laporBmasukActionPerformed

    private void LaporBkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporBkeluarActionPerformed
      try {
    // Lokasi file .jasper (file hasil compile dari .jrxml)
    String namaFile = "src/tampilan/barang_keluar.jasper";
    Connection con = new koneksi().connect();
    // Parameter untuk report, bisa dikosongkan jika tidak ada parameter
    HashMap<String, Object> parameter = new HashMap<>();
    // File report
    File report_file = new File(namaFile);
    // Load report (gunakan variabel report_file agar konsisten)
    JasperReport report = (JasperReport) JRLoader.loadObject(report_file);
    // Isi report dengan data dari database
    JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameter, con);
    // Tampilkan report
    JasperViewer.viewReport(jasperPrint, false);
    JasperViewer.setDefaultLookAndFeelDecorated(true);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error menampilkan laporan: " + e.getMessage());
}                 // TODO add your handling code here:
    }//GEN-LAST:event_LaporBkeluarActionPerformed

    private void LaporsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporsupActionPerformed
  try {
    // Lokasi file .jasper (file hasil compile dari .jrxml)
    String namaFile = "src/tampilan/supplier.jasper";
    Connection con = new koneksi().connect();
    // Parameter untuk report, bisa dikosongkan jika tidak ada parameter
    HashMap<String, Object> parameter = new HashMap<>();
    // File report
    File report_file = new File(namaFile);
    // Load report (gunakan variabel report_file agar konsisten)
    JasperReport report = (JasperReport) JRLoader.loadObject(report_file);
    // Isi report dengan data dari database
    JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameter, con);
    // Tampilkan report
    JasperViewer.viewReport(jasperPrint, false);
    JasperViewer.setDefaultLookAndFeelDecorated(true);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error menampilkan laporan: " + e.getMessage());
}                      // TODO add your handling code here:
    }//GEN-LAST:event_LaporsupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LaporBkeluar;
    private javax.swing.JButton Laporsup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporBmasuk;
    private javax.swing.JButton laporstok;
    private javax.swing.JPanel panelLaporan;
    // End of variables declaration//GEN-END:variables
}
