/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Who_Im_I
 */
public class MenuTransaksi extends javax.swing.JPanel {

    private JPanel panelTarget;  // Tipe diperbaiki jadi JPanel

    public MenuTransaksi(JPanel panelTarget) {
        this.panelTarget = panelTarget;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnutransaksi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        brngmsk = new javax.swing.JButton();
        brngkeluar = new javax.swing.JButton();
        mtsibrng = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mnutransaksi.setBackground(new java.awt.Color(255, 255, 255));
        mnutransaksi.setMaximumSize(new java.awt.Dimension(271, 322));
        mnutransaksi.setMinimumSize(new java.awt.Dimension(271, 322));
        mnutransaksi.setPreferredSize(new java.awt.Dimension(271, 322));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Transaksi");

        brngmsk.setBackground(new java.awt.Color(255, 255, 255));
        brngmsk.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        brngmsk.setText("Barang Masuk");
        brngmsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brngmskActionPerformed(evt);
            }
        });

        brngkeluar.setBackground(new java.awt.Color(255, 255, 255));
        brngkeluar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        brngkeluar.setText("Barang Keluar");
        brngkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brngkeluarActionPerformed(evt);
            }
        });

        mtsibrng.setBackground(new java.awt.Color(255, 255, 255));
        mtsibrng.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        mtsibrng.setText("Mutasi Barang");
        mtsibrng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtsibrngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnutransaksiLayout = new javax.swing.GroupLayout(mnutransaksi);
        mnutransaksi.setLayout(mnutransaksiLayout);
        mnutransaksiLayout.setHorizontalGroup(
            mnutransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnutransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnutransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mnutransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mnutransaksiLayout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addGroup(mnutransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(brngkeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mtsibrng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brngmsk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
        );
        mnutransaksiLayout.setVerticalGroup(
            mnutransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnutransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(brngmsk)
                .addGap(26, 26, 26)
                .addComponent(brngkeluar)
                .addGap(26, 26, 26)
                .addComponent(mtsibrng)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        add(mnutransaksi, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void brngmskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brngmskActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_brngmskActionPerformed

    private void brngkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brngkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brngkeluarActionPerformed

    private void mtsibrngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtsibrngActionPerformed
    panelTarget.removeAll();
    panelTarget.setLayout(new BorderLayout());
    panelTarget.add(new MutasiBarang1(), BorderLayout.CENTER);
    panelTarget.revalidate();
    panelTarget.repaint();  // TODO add your handling code here:
    }//GEN-LAST:event_mtsibrngActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brngkeluar;
    private javax.swing.JButton brngmsk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mnutransaksi;
    private javax.swing.JButton mtsibrng;
    // End of variables declaration//GEN-END:variables
}
